version: "3.7"

services:
    # image project
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - monitorsites

    # nginx
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - monitorsites

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3379:3306"
        networks:
            - monitorsites

    # redis
    redis:
        image: redis:latest
        restart: always
        networks:
            - monitorsites

networks:
    monitorsites:
        driver: bridge
