version: "3"

services:
    # image project
    app:
        build:
            args:
                user: ${APP_USER}
                uid: ${APP_UID}
            context: ./docker/8.1
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '8989:80'
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - monitor_sites

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - monitor_sites

    # redis
    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - monitor_sites

networks:
    monitor_sites:
        driver: bridge
